#!/bin/bash
docker stop oxidized
docker rm oxidized
docker build -q -t oxidized/oxidized:latest .
docker run -v /etc/oxidized/:/root/.config/oxidized -p 8000:8888/tcp --name oxidized -t oxidized/oxidized:latest oxidized
